project:
  type: website
  output-dir: docs

website:
  title: "Yanyang Chen - MUSA 5080 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: weekly-notes/week-01-notes.html
        text: Weekly Notes
      - href: assignments/assignment2.html
        text:assignments

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto
